### ISSUE TITLE
Invalid pack schema

### ISSUE THREAD

**Issue by zwass** [teoseller/osquery-attck#3]
Thanks for the cool work here! I noticed that the schema for this pack is incorrect: https://github.com/teoseller/osquery-attck/blob/master/network_connection_listening.conf#L32. Maybe that description is supposed to be included with one of the queries?

**Comment by teoseller** [comment]
Hi Zach good morning, thank for the message
I try do give you an explanation about the "description" section
with the description i would like to show all the mitre techniques within the query pack, just to have all the techniques listed in one row
In all the query pack there is a description row.
do you have an error when  you try to use the query pack ?

**Comment by teoseller** [comment]
changed the pack schema thanks to zwass.
